apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"headlamp","namespace":"kube-system"},"spec":{"ports":[{"port":80,"targetPort":4466}],"selector":{"k8s-app":"headlamp"}}}
    name: headlamp
    namespace: kube-system
  spec:
    ports:
    - port: 80
      targetPort: 4466
    selector:
      k8s-app: headlamp
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"headlamp","namespace":"kube-system"},"spec":{"replicas":1,"selector":{"matchLabels":{"k8s-app":"headlamp"}},"template":{"metadata":{"labels":{"k8s-app":"headlamp"}},"spec":{"containers":[{"args":["-in-cluster","-plugins-dir=/headlamp/plugins"],"image":"ghcr.io/headlamp-k8s/headlamp:latest","livenessProbe":{"httpGet":{"path":"/","port":4466,"scheme":"HTTP"},"initialDelaySeconds":30,"timeoutSeconds":30},"name":"headlamp","ports":[{"containerPort":4466}]}],"nodeSelector":{"kubernetes.io/os":"linux"}}}}}
    name: headlamp
    namespace: kube-system
  spec:
    replicas: 1
    selector:
      matchLabels:
        k8s-app: headlamp
    template:
      metadata:
        labels:
          k8s-app: headlamp
      spec:
        containers:
        - args:
          - -in-cluster
          - -plugins-dir=/headlamp/plugins
          image: ghcr.io/headlamp-k8s/headlamp:latest
          livenessProbe:
            httpGet:
              path: /
              port: 4466
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 30
          name: headlamp
          ports:
          - containerPort: 4466
        nodeSelector:
          kubernetes.io/os: linux
- apiVersion: v1
  kind: Secret
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{"kubernetes.io/service-account.name":"headlamp-admin"},"name":"headlamp-admin","namespace":"kube-system"},"type":"kubernetes.io/service-account-token"}
      kubernetes.io/service-account.name: headlamp-admin
    name: headlamp-admin
    namespace: kube-system
  type: kubernetes.io/service-account-token
kind: List
metadata: {}
