apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp-app
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: headlamp
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://headlamp-k8s.github.io/headlamp/
    targetRevision: 0.25.0
    chart: headlamp
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
