apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-sql
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: my-sql
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 11.1.17
    chart: my-sql
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
