apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: first-app
spec:
  destination:
    name: ''
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: ./
    repoURL: https://github.com/shlatshwayo/CloudNative.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
